# Generated by Django 3.0.4 on 2020-03-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('alamat', models.CharField(max_length=100)),
                ('flag', models.FileField(blank=True, null=True, upload_to='static/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_matkul', models.CharField(max_length=50)),
                ('nama_matkul', models.CharField(max_length=255)),
                ('sks', models.IntegerField(default=0, verbose_name='The number of Repositories')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Dosen', to='management.Dosen')),
            ],
        ),
    ]
