# Generated by Django 2.2.6 on 2020-03-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('nip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('alamat', models.CharField(max_length=100, null=True)),
                ('flag', models.FileField(blank=True, null=True, upload_to='static/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('kode_matkul', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_matkul', models.CharField(max_length=255)),
                ('sks', models.IntegerField(default=0, verbose_name='SKS')),
                ('nip', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matkul', to='management.Dosen')),
            ],
        ),
        migrations.CreateModel(
            name='Mengikuti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_matkul', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mengikuti', to='management.Matkul')),
                ('nim', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mengikuti', to='management.Mahasiswa')),
            ],
        ),
    ]
