# Generated by Django 3.0.4 on 2020-03-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matkul',
            old_name='country',
            new_name='nip',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='id',
        ),
        migrations.RemoveField(
            model_name='matkul',
            name='id',
        ),
        migrations.AlterField(
            model_name='dosen',
            name='nip',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matkul',
            name='kode_matkul',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
